markdown: redcarpet
highlighter: pygments
rdiscount:
  extensions: [smart]
timezone: DE


permalink: /:title


destination: _site


paginate: 5
paginate_path: "blog/page:num/"


base_url: "http://www.padrinorb.com/"

# Site settings
title: Padrino
email: members@padrinorb.com
description: "Padrino is a ruby framework built upon the excellent Sinatra Microframework. This framework tries hard to make it as fun and easy as possible to code much more advanced web applications by building upon the Sinatra philosophies and foundation."


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF0000
  secondary: FF0000
  secondary-dark: 333


# yaml default setup
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "guides"
      type: "pages"
    values:
      layout: "guides"
  -
    scope:
      path: "team"
      type: "pages"
    values:
      layout: "team"
  -
    scope:
      path: "blog"
      type: "pages"
    values:
      layout: "blog"


gems:
  - jekyll-sitemap
  - jekyll-mentions


jekyll-mentions: https://github.com


# Team names, titles and social links
people:
- name: DAddYE
  pic: daddye
  position: He lives, works, and plays in SF.
  social:
    - title: home
      url: http://www.daddye.it/
    - title: twitter
      url: https://www.twitter.com/DAddYE
    - title: github
      url: https://github.com/DAddYE
- name: Uchio Kondo
  pic: kondo
  position: Is the official maintainer of 日本語 Padrino.
  social:
    - title: twitter
      url: https://twitter.com/udzura
    - title: github
      url: https://github.com/udzura
- name: namusyaka
  pic: namusyaka
  position: I'm a ruby programmer born in Japan.
  social:
    - title: home
      url: http://namusyaka.info/
    - title: twitter
      url: https://twitter.com/namusyaka
    - title: github
      url: https://github.com/namusyaka
- name: Darío Javier Cravero
  pic: dario
  position: Loves to innovate and create simple yet great solutions.
  social:
    - title: home
      url: http://www.uxtemple.com/
    - title: twitter
      url: https://twitter.com/dariocravero
    - title: github
      url: https://github.com/dariocravero
- name: Igor Bochkariov
  pic: igor
  position: Loves Ruby and web programming and tries to keep Padrino lean and mean.
  social:
    - title: home
      url:  http://ujifgc.tumblr.com/
    - title: twitter
      url: https://twitter.com/ujifgc
    - title: github
      url: https://github.com/ujifgc
- name: Nathan Esquenazi
  pic: nathan
  position: Used to also do freelance work using Rails and Padrino.
  social:
    - title: home
      url: http://codepath.com/
    - title: twitter
      url: https://twitter.com/nesquena
    - title: github
      url: https://github.com/nesquena
- name: Arthur Chiu
  pic: achiu
  position: He enjoys programming, martial arts, and traveling when he has the time.
  social:
    - title: home
      url: http://www.arthurchiu.com/#/
    - title: twitter
      url: https://twitter.com/arthur_chiu
    - title: github
      url: https://github.com/achiu
- name: Florian Gilcher
  pic: florian
  position: He uses his own mashup of Sinatra and many parts of Padrino for it.
  social:
    - title: home
      url: http://asquera.de/
    - title: twitter
      url: https://twitter.com/skade
    - title: github
      url: https://github.com/skade
- name: Joshua Hull
  pic: joshua
  position: Joshua loves his Ruby, and loves making awesome web apps.
  social:
    - title: twitter
      url: https://twitter.com/joshbuddy
    - title: github
      url: https://github.com/joshbuddy

social:
  - title: twitter
    url: http://twitter.com/padrinorb
  - title: github
    url: http://github.com/padrino
  - title: rss
    url: /feed.xml


exclude:
  - Gemfile
  - Gemfile.lock
  - plugins
  - Rakefile
  - bin
