source 'https://rubygems.org'

gem 'colorator'   , '0.1.0'
gem 'cssminify'   , '1.0.2'
gem 'fileutils'
gem 'highline'    , '1.6.21'
gem 'jekyll'      , '2.5.3'
gem 'jekyll-mentions', '0.1.3'
gem 'jekyll-sitemap', '0.6.2'
gem 'rake'        , '10.3.2'
gem 'stringex'    , '2.5.2'
gem 'uglifier', '2.7.0'
